import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// const ibmPlexSans = IBM_Plex_Sans({
//   display: "swap",
//   subsets: ["latin"],
//   weight: ["500", "600", "700"],
// });

const ibmPlexSans = localFont({
  src: [
    {
      path: "../public/fonts/IBM_Plex_Sans/IBMPlexSans-Bold.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/IBM_Plex_Sans/IBMPlexSans-BoldItalic.ttf",
      weight: "700",
      style: "italic",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ibmPlexSans.className}>{children}</body>
    </html>
  );
}
